name: JSON functions
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }}
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}
