name: Add mask
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: SuperSecretValue
    steps:
      - run: echo "デバッグ"
      - run: echo "${PASSWORD}"
      - run: ::add-mask::${PASSWORD}
      - run: echo "${PASSWORD}"
