name: Conditions Workflow
on: push
jobs:
  skip-or-run-1:
    if: ${{ github.actor == 'octcat' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, octcat"
    if: ${{ github.actor == 'karlley' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, karlley"
